version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /git-contribution-graph
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
