[display]
dataframes = "rich"
cell_output = "below"
default_width = "wide"
theme = "system"
code_editor_font_size = 18

[formatting]
line_length = 80

[keymap]
preset = "vim"
[keymap.overrides]
"cell.createAbove" = "Ctrl-Shift-:"
"cell.createBelow" = "Ctrl-;"

[package_management]
manager = "uv"

[runtime]
auto_instantiate = true
auto_reload = "off"
std_stream_max_bytes = 1000000
on_cell_change = "autorun"
output_max_bytes = 8000000
watcher_on_save = "lazy"
pythonpath = []

[save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"

[server]
browser = "default"
follow_symlink = false

[snippets]
include_default_snippets = true
custom_paths = []

# Miscellanea
[completion]
copilot = "github"
activate_on_typing = true

[ai]
rules = ""
[ai.anthropic]
[ai.open_ai]
[ai.google]

[experimental]
chat_sidebar = true
tracing = true
