[snippets]
include_default_snippets = true
custom_paths = []

[ai]
rules = ""
mode = "manual"

[ai.open_ai]

[ai.anthropic]

[ai.google]

[ai.models]
edit_model = "anthropic/claude-sonnet-4-20250514"
chat_model = "anthropic/claude-sonnet-4-20250514"
displayed_models = ["anthropic/claude-sonnet-4-20250514", "google/gemini-2.5-flash", "google/gemini-2.5-pro"]
custom_models = []

[keymap]
destructive_delete = true
preset = "vim"

[keymap.overrides]
"cell.createAbove" = "Ctrl-Shift-:"
"cell.createBelow" = "Ctrl-;"

[package_management]
manager = "uv"

[experimental]
chat_sidebar = true
tracing = true

[formatting]
line_length = 80

[runtime]
watcher_on_save = "lazy"
default_sql_output = "auto"
pythonpath = []
reactive_tests = true
auto_reload = "off"
auto_instantiate = true
std_stream_max_bytes = 1000000
default_auto_download = []
on_cell_change = "autorun"
output_max_bytes = 8000000

[diagnostics]

[server]
browser = "default"
follow_symlink = false

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enabled = true
enable_mypy = true
enable_ruff = true
enable_pyflakes = false
enable_pylint = false
enable_flake8 = false
enable_pydocstyle = false

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[completion]
activate_on_typing = true
copilot = "github"

[display]
cell_output = "below"
default_table_max_columns = 50
dataframes = "rich"
theme = "system"
reference_highlighting = false
default_width = "full"
default_table_page_size = 10
code_editor_font_size = 18
